---
- name: Dnf enabling repos
  become: true
  become_user: root
  with_items: '{{ r_dnf_repos | default([]) }}'
  ansible.builtin.command: dnf config-manager --enable '{{ item }}'
  changed_when: false
