---
- name: (Debian) installing....
  when: ansible_os_family == "Debian"
  include: Debian.yml

- name: (EL) installing....
  when: ansible_os_family == "RedHat"
  include: EL.yml

- name: install r-dynamic-install.r
  copy: >
    src=r-dynamic-install.r
    dest=/usr/local/bin
    mode=0755
    owner=root
    group=root
    
- name: installing R packages...
  command: /usr/local/bin/r-dynamic-install.r {{item}}
  with_items: '{{r_pkgs}}'
  
  
