---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: (Debian) configuring apt....
  become: yes
  become_user: root
  when: ansible_os_family == "Debian"
  include: apt.yml

- name: installing R core/base packages...
  become: yes
  become_user: root
  with_items: '{{r_base_pkg_list|default([])}}'
  package:
    name: '{{item}}'
    state: present

- name: install R module os specific packages
  become: yes
  become_user: root
  with_items: '{{r_os_pkgs|default([])}}'
  package:
    name: '{{r_os_pkg_prefix}}{{item}}'
    state: present
  
- name: install r-dynamic-install.r
  become: yes
  become_user: root
  with_items:
    - r-dynamic-install.r
  template:
    src: '{{item}}.j2'
    dest: /usr/local/bin/{{item}}
    mode: 0755
    
- name: installing R packages...
  become: yes
  become_user: root
  command: /usr/local/bin/r-dynamic-install.r {{item}}
  with_items: '{{r_pkgs|default([])}}'
  
  
