---
- include_role:
    name: andrewrothstein.epel
- include_role:
    name: andrewrothstein.gpg
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: (Debian) configuring apt....
  when: ansible_os_family == "Debian"
  include_tasks:
    file: apt.yml
    apply:
      become: true
      become_user: root

- name: installing R core/base packages...
  become: true
  become_user: root
  with_items: '{{ r_base_pkg_list | default([]) }}'
  package:
    name: '{{ item }}'
    state: present

- name: install R module os specific packages
  become: true
  become_user: root
  with_items: '{{ r_os_pkgs | default([]) }}'
  package:
    name: '{{ r_os_pkg_prefix }}{{ item }}'
    state: present

- name: install r-dynamic-install.r
  become: true
  become_user: root
  with_items:
    - f: r-dynamic-install.r
      d: '{{ r_dynamic_installer_path }}'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0755") }}'

- name: installing R packages...
  become: true
  become_user: root
  with_items: '{{ r_pkgs | default([]) }}'
  command: '{{ r_dynamic_installer_path }}/r-dynamic-install.r {{ item }}'
