---
- name: (Ubuntu) installing....
  when: ansible_distribution == "Ubuntu"
  include: Ubuntu.yml

- name: (Fedora) installing....
  when: ansible_distribution == "Fedora"
  include: Fedora.yml

- name: install r-dynamicy-install.r
  copy: >
    src=r-dynamic-install.r
    dest=/usr/local/bin
    mode=0755
    owner=root
    group=root
    
- name: installing R packages...
  command: /usr/local/bin/r-dynamic-install.r {{ item }}
  with_items:
    - shiny
    - rmarkdown
    - dplyr
    - ggplot2
    - Rcpp
    - rJava
    - e1071
    - packrat
  
  
