---
- name: Installing andrewrothstein.epel
  ansible.builtin.include_role:
    name: andrewrothstein.epel
- name: Installing andrewrothstein.gpg
  ansible.builtin.include_role:
    name: andrewrothstein.gpg
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Using pkg manager {{ r_pkg_mgr }}
  when: r_pkg_mgr is defined
  ansible.builtin.include_tasks: '{{ r_pkg_mgr }}.yml'

- name: Installing R core/base packages...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ r_base_pkg_list | default([]) }}'
    state: present

- name: Install R module os specific packages
  become: true
  become_user: root
  with_items: '{{ r_os_pkgs | default([]) }}'
  ansible.builtin.package:
    name: '{{ r_os_pkg_prefix }}{{ item }}'
    state: present

- name: Install r-dynamic-install.r
  become: true
  become_user: root
  with_items:
    - f: r-dynamic-install.r
      d: '{{ r_dynamic_installer_path }}'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("755") }}'

- name: Installing R packages...
  become: true
  become_user: root
  with_items: '{{ r_pkgs | default([]) }}'
  ansible.builtin.command: '{{ r_dynamic_installer_path }}/r-dynamic-install.r {{ item }}'
  changed_when: false
